#!/usr/bin/bash

FILE="$HOME/cheatsheets/pages/$1"

if [ -d $FILE ]; then
	vim $FILE
else
	if [ ! -e "$FILE.md" ]; then
		install -Dv /dev/null "$FILE.md" # Create file with all necessary parents
	fi
	vim "$FILE.md" # Edit said file
fi
