#!/usr/bin/bash


FILE="$HOME/cheatsheets/pages/$1"

if [ -d $FILE ]; then
	ls -1 $FILE
else
	if [ -f "$FILE.md" ]; then
		# pandoc translate markdown file to bash readable format and we just display it
		pandoc -s -f markdown -t man "$FILE.md" | man -l -
	else
		echo "This cheatsheet doesn't exist yet"
		echo "Use cheatsheet-edit [CHEATSHEET NAME] to create it"
	fi
fi
